#!/usr/bin/env bash
#a Bash script that stops 4-to_infinity_and_beyond process

id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#terminating the infinite process
if [ -n "$id" ]
then
	kill -15 "$id"
fi
