#!/usr/bin/env bash
#a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
number=0
while [ $number -lt 10 ]
do
	if [ $number -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((number++))
done
